name: Daily Repository Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC (specific time, no wildcards)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Adjust to 'master' if your default branch differs
          fetch-depth: 0  # Full history for commits

      - name: Update status log by 23f3000833@ds.study.iitm.ac.in
        run: |
          echo "$(date): Daily automated update for activity tracking, documentation, backup, and compliance." >> status.log

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Daily automated commit - ${{ github.run_number }}
          file_pattern: status.log
